### ISSUE TITLE
Removal Requests and Proposed Changes

### ISSUE THREAD

**Issue by Reagy** [Reagy/TF2Classic-KO-Custom-Weapons#105]
This ticket will be used to log removal requests and pending removals.

If you have any items you would rather see removed, please suggest them here, along with the reasoning.

EDIT VIA WONDERS: This list may or may not be accurate to the future of Knockout!

The development of V6 will basically be a complete overhaul of the current sandbox, leave any suggestions here in terms of balance feedback but I'm 95% confident I've changed most if not all weapons of concern.

I do read things here btw so keep posting them, we'll start logging removal and change requests post-v6.

Cheers for your attention.

Current Removal List:
[ CURRENTLY UNAVAILABLE]

Proposed Changes:
[ CURRENTLY UNAVAILABLE]

Previous Removal List:
[ CURRENTLY UNAVAILABLE]

Previous Proposed Changes:
[ CURRENTLY UNAVAILABLE]

**Comment by Baruze** [comment]
Combine or rework one of the 2 spy suits, please.
Security Measure & Major's mask are too similar in stats.
The MGS one is cooler, tbh.

**Comment by Reagy** [comment]
> Combine or rework one of the 2 spy suits, please. Security Measure & Major's mask are too similar in stats. The MGS one is cooler, tbh.

Honestly, you're right on that one.
Security Measure will be merged into the Major's Mark, as it is more visually distinct between the two.

**Comment by Reagy** [comment]
> can the makeshift mutilator be either reworked or removed? I feel it gets outclassed as a self-sustaining primary by two other flamethrowers that pyro has, one of which is also not very good

I'm honestly not happy with how this one current sits and personally, don't think it should have ever been changed into its current form. The older revision of the item was far more engaging and fun to use, even if it was just funny number goes ding with lower base damage.

Might revert it back into its old form.

**Comment by TheRealAtomicDemoman** [comment]
can the stainless scorcher and burning vengeance get an accuracy buff? cus the already limited range of both shotguns are even more limited by spread and you got no airblast to even defend yourself. they both deal good damage but the accuracy makes damage from any distance other than melee really low

**Comment by TheHopeBunny** [comment]
can the malicious multitools be reworked a little where they can perform fine enough without the need of having both in the same loadout? right now the multitools are SUPER restricted and are usually only successful when you use both the primary AND melee versions, which I suppose is the point of them, but they're also just a somewhat worse version of the flamethrower into propain playstyle which performs a lot better due to the propain having extended range

**Comment by Plaguewalker** [comment]
Lower the speed stat of the fox tail on scout it's obvious there's quite a vocal minority outside of the "lol furries bad" in regards to the way it's handled as trying to fight a max cap speed scout that knows how use it is more of a pain to fight. Lowering the speed from 33% to 25% would still give the scout an advantage in terms of movement without completely nullifying the items purpose

**Comment by TheHopeBunny** [comment]
can the super nail gun have it's max ammo increased? it seems to run out of ammo a LITTLE too quickly for the damage it deals

**Comment by RurikArvallen** [comment]
Since Conagher Classic and Building Upgrader are now on the chopping block, perhaps it's time to revert the changes on the Texas Strongmann. Maybe to an older version where it couldn't directly repair buildings but with the added change that building upgrade cost to lv2 and lv3 is 400 and 600 metal instead of just 200 as a way to balance out how quickly some of Engie's primaries can deal damage.

**Comment by TheHopeBunny** [comment]
can the beeg boris receive a clip size buff from 2 to 3? I love its design AND the fact that you can use it as a mobility tool.. but I kinda wished its dps was buffed in some way
also I really don't like how certain weapons or items in video games get balanced around the fact the idea of them being "mobility tools". thats why I fucking HATED the sputnik special in the previous versions of kocw since it tended to make heavy a LOT worse since he doesn't have any variant of the market gardener AND doesn't have a full-auto secondary weapon so why would you even trade one of THE strongest primary weapons for what is effectively a slow-firing rocket jumper? it just never made ANY sense to me. like I get that it could be fun to blast jump across the map as a heavy, but you're trading the MINIGUN for a TOY.

also sorry that this devolved into a rant about the sputnik special being terrible.

**Comment by Reagy** [comment]
> ### Trench Breaker Rework
> 
> The **Trench Breaker** is, in its current position, a weapon you will not be using unless for the specific purpose of destroying an engineer nest. A weapon that you will only use in a very specific circumstance for only a couple lives is generally not a good idea for weapon balance. I suggest that the projectile speed is kept, along with the clip size reduction and damage penalty, but reduce the building damage to 50% or so and remove the splash damage penalty altogether. I posit that a few new stats to add would be to actually _increase its splash radius_ (I don't have a specific number because I don't know the exact size of splash damage to begin with, just whatever can deal damage to everyone in a group but have minimal damage to those outside of a group) and if possible, **make the grenades break and not explode upon hitting a surface. If it is not possible to have grenades break upon hitting a non-player, this idea should probably be disregarded** because I think this shouldn't be too spamable. This is kind of a hit or miss because I can't tell how annoying this would be to play against. Just **use your best judgement** during weapon testing.

This will be something we'll have to look into more with 2.1's release, believe there will be attributes to allow this. At the moment, been considering canning the Breaker as there are enough nest busting weapons on demo.

**Comment by TheHopeBunny** [comment]
I don't think I see the Your Darkest Nightmare revolver being used very much. I'd suggest either a total rework of it to make it a little more interesting or just removing it entirely.

**Comment by TheHopeBunny** [comment]
Also, I feel as though that the Centurian Command is GROSSLY overshadowed by the Gorey Gladiator, which might be due to the Gorey Gladiator's superior health regen and the fact that it, unlike the CC, increases your move speed by 25%.
Instead of suggesting that the Centurian Command get removed, I honestly REALLY don't like that idea. I think either it or both armors should be *S L I G H T L Y* redesigned a bit so that both grant a speed boost? But the Gorey Gladiator still provides a significantly *better* speed boost in comparison?

**Comment by MadHuntress** [comment]
> > ### Trench Breaker Rework
> > The **Trench Breaker** is, in its current position, a weapon you will not be using unless for the specific purpose of destroying an engineer nest. A weapon that you will only use in a very specific circumstance for only a couple lives is generally not a good idea for weapon balance. I suggest that the projectile speed is kept, along with the clip size reduction and damage penalty, but reduce the building damage to 50% or so and remove the splash damage penalty altogether. I posit that a few new stats to add would be to actually _increase its splash radius_ (I don't have a specific number because I don't know the exact size of splash damage to begin with, just whatever can deal damage to everyone in a group but have minimal damage to those outside of a group) and if possible, **make the grenades break and not explode upon hitting a surface. If it is not possible to have grenades break upon hitting a non-player, this idea should probably be disregarded** because I think this shouldn't be too spamable. This is kind of a hit or miss because I can't tell how annoying this would be to play against. Just **use your best judgement** during weapon testing.
> 
> This will be something we'll have to look into more with 2.1's release, believe there will be attributes to allow this. At the moment, been considering canning the Breaker as there are enough nest busting weapons on demo.

Yeah in my opinion getting rid of the Trench Breaker until 2.1 is a good idea.

**Comment by nosoytunose** [comment]
Afterburner slight buff:
tbh, at this moment,the afterburner is kinda...lame,with the damage penalty along with ammo consuption,although i think its fine in this state right now...i have a problem...pyros,if you have the afterburner equipped,you cant do shit about enemy pyros,i would suggest allowing it to afterburn pyros....and adding the healing afterburn too,because why not,its a afterburn focused flame after all

**Comment by TheHopeBunny** [comment]
the pneumatic pulverizer feels a little.. *weak* for a primary.. can it get some kind of slight damage buff?

**Comment by TheHopeBunny** [comment]
Also.. the Storage Backpack is kind of terrible? And is also *entirely outclassed* by the Engie's Geared-Up Ghost secondary, since that not ONLY also gives 50 extra max metal, but it also increases his max primary ammo by 50%.
Meanwhile the Storage Backpack gives 50 extra max metal at the cost of making you slower and lowering your effective max health. It's just not even CLOSE to being a good primary item. I'd say it should be changed and reworked to do something else entirely or just. Get got.

**Comment by Baruze** [comment]
Add a no random crits attribute to the Elimination Imperative loadout description.
AFAIK it doesn't deal random crits anyway.
In the case that I was wildly unlucky and it DOES deal random crits, I think they'd be an unnecessary addition.
The weapon is already pretty good.

**Comment by nosoytunose** [comment]
a slight buff to drunkards wrath.
right now..it feels mediocre,you want spammy?
you have caber toss ,slam blaster and ol brimstone
you want a quick kill without needing to rely on a single shot?
bouncy bety 
Quick proyectile?
artizans or ultimatum
single high damage?
cyclops and caber toss

maybe a reload speed buff?
or the removal of the explotion radius penalty?

**Comment by pro-medic-main** [comment]
i saw that the spy fly was removed, it was one of my favourite spy weapons as it gave the spy mobility for the lack of a revolver and self defence. was there a reason for the removal or just for clearing it for new spaces?

**Comment by nosoytunose** [comment]
fire startes is right now neglected sadly to engie bitching,all his stats are focused on screwing spies.
i would suggest removing the afterburn penalty ,so its a great "fight starter" it even makes sense with the name,
fire starter
fight starter
even better replace it with a afterburn bonus,it wouldnt hurt

**Comment by TheHopeBunny** [comment]
I like the idea of the Pip-Boy 1950 making engineer into much more of an offensive class, but I feel like it sort of underperforms in this idea due to it only increasing your max health by 25 and also completely gimping your ability to upgrade your buildings. Can the Pip-Boy increase your walkspeed a little bit? Or have a less harsh upgrading penalty?

**Comment by TheHopeBunny** [comment]
The Tinkerer's Tetra-Shot is a cool idea, being a burst-firing gun that uses metal for ammo. Unfortunately, I feel like its DPS is a bit low.. I suggest increasing the amount of bullets fired in each burst from 5 to 6 or 7, not a straight-up damage increase as I feel that may not be very balanced.

**Comment by TheHopeBunny** [comment]
The Malicious Mac is.. well.. it's bad. It FEELS and LOOKS like the Ghetto Blaster.. if it was relentlessly beaten to a pulp for several hours in the snow. I suggest increasing its clip size to either 15 or 20.

**Comment by TheHopeBunny** [comment]
Can the Rosemary's +10% stats be increased by just a little bit? Maybe to +15% each? Or even +20% each? Or +20% Damage and +15% Accuracy?

**Comment by TheHopeBunny** [comment]
> Can the Rosemary's +10% stats be increased by just a little bit? Maybe to +15% each? Or even +20% each? Or +20% Damage and +15% Accuracy?

I say this because, other than the unique attribute of it dealing crits to crit-boosted players, it otherwise mostly feels like a slightly worse stock scattergun?

**Comment by TheHopeBunny** [comment]
Can the throwing knives apply bleed on hit at the cost of dealing 45-50 damage per hit instead of 60? Right now they feel kinda.. eh. Like there's not really much to say about them in the first place, they're just kinda. There. Being a little bit boring.

**Comment by TheHopeBunny** [comment]
Can the Displacer Cannon have a much less harsh blast radius penalty? It's not really *that* powerful to the point that it deserves a blast radius penalty of that size.

**Comment by TheHopeBunny** [comment]
Man the Spitfire is.. well.. it exists. And is also kinda maybe. Not that good.
It doesn't seem to fire fast enough to justify the huge damage penalty, not to mention that the upside that direct hits have no damage falloff seem to be almost completely negated due to the +2 degrees of rocket deviation. I would suggest that the rocket deviation downside be completely removed so that it would suck marginally less.

**Comment by TheHopeBunny** [comment]
Can the Executor get several buffs? Right now it.. kinda just feels like a hitscan flaregun.. that cannot ignite enemies. Nor deals enough damage to be good *without* the afterburn that flareguns provide. Honestly it's overall just objectively bad compared to every single other secondary that Pyro has access to, including the stock shotgun.

**Comment by TheHopeBunny** [comment]
Can the Prosecutor deal a LOT more damage?? Right now it.. barely does ANYTHING to enemies. Like, it literally deals around 5-8 damage per hit. This thing is a LOT worse than the Executor lol.

**Comment by TheHopeBunny** [comment]
Okay, from here on out I will now try to keep the majority of my requests in one message instead of constantly spamming the entire thing.

(Warning: This is gonna be long. I am sorry in advance.)

For All/Most Classes..

Can the Brickhouse Beatdown get either a damage increase on direct hits or have a projectile speed increase? I know its projectile speed increases the longer you charge, but.. with the damage it deals on hit, it really isn't that good. Especially not for classes that have far superior options for throwable projectiles/explosives (COUGH knives COUGH grenade COUGH caber toss COUGH)

For Soldier..

Can the grenades deal 120 damage on direct hits *instead* of 135? It's really not that fun to fight against a soldier that can just one-tap you with a single grenade. This isn't Call Of Duty, it's Tea For Two.

For Pyro..

Can the Multitools be made so that they can work *without* needing both of them? Right now it seems that the only viable way to use the Multitools is by using the primary to damage an enemy and then land a guaranteed crit on them with the melee. Like I've said before, this seems like a less successful version of the primary/secondary into Propain combo which is a LOT more versatile.

Can the Molotov Launcher's projectiles move faster?? Right now it's.. generally just a mediocre, maybe even bad weapon that is outclassed by nearly every other Pyro primary.

Can the Magic Wand APPLY bleed instead of Afterburn, in exchange for no longer dealing more damage to bleeding enemies? Because the only other weapon that CAN apply bleed on hit is a melee weapon that doesn't have an extended range like the Propain. Speaking of which..

Can the Glacial Gouger have an extended range? Because as it is right now, Propain loadouts are a LOT more successful than Gouger loadouts purely due to the Propain's larger melee range. The Gouger not only doesn't have *this*, but it ALSO has MUCH fewer options for applying bleed at a range further than melee.

For Demo..

NERF THE CABER TOSS'S DAMAGE OUTPUT HOLY SHIT IT IS VERY FRUSTRATING TO FIGHT AGAINST AS A LIGHT CLASS.

Can the Ultimatum apply.. something, on a direct hit? Right now it's.. kinda just there. There's also not a whole lot of reason to use it over the other primaries that have grenades that move faster.

Can the Combat Control have a *slightly* faster firerate? I feel as though it may not be super useful when used to save yourself from self-damage when an enemy is all up in your face considering its slow firerate.

Can the Drunkard Brawling deal more than, like.. 25 damage?? Right now it's a MUCH worse stock BAT with very diminishing returns.

Can the Unusual Tale Of Tragedy attack while you're invisible? I get that going invisible after killing someone might be for you to run away to a health pack or whatever, but then why have the health gain on kill? Also, the slower move speed with it only makes it even HARDER to flee considering that Demoknight here is already usually too slow on foot.

For Heavy..

Considering that the Van De Graaf exists now, can the Warsaw Fact have its movespeed bonus increased from +20% to +25% or +30%? Right now it seems to make people think that its just a worse Van De Graaf simply due to its far shorter range.

Can the Dirty Bomb have a slightly faster firerate? Right now it feels much too slow, especially compared to the firerate of the stock Rocket Launcher.. and even the RNG (RPG).

can the funny borger on heavy just. get snapped.
he already has the sandvich, theres literally no reason for him to have another lunch item that functions EXACTLY the same.

Can the Laika III's spinup time be a little faster? Right now it's WAAAY too slow, especially for when you get ambushed by a random Pyromaniac about to smash your head in with their funny crit sticc.

For Engineer..

Can the Nail Storm function a *bit* more differently from the Rust Valley Relic? Right now it sorta just feels like a RVR that fires projectiles instead of hitscan bullets and also doesn't restore health on hit. And also makes you move even slower than the actual RVR.
..in fact the Nail Storm is sort of just. The RVR but weaker? Like, what is the point of it? I love the model and I love firing lots of nails at enemies, but if I want an Engie primary that fires very fast at the cost of making me move slower, I'll mostly just go with the RVR over the Nail Storm.

Can the Pneumatic Pulverizer get a SLIGHT damage increase? Right now it's somewhat overshadowed by the RVR, Nail Storm, and even the Tinkerer's Tetra-Shot and Problem Solver. Alternatively, can it affect Sentry range? Teleporter build speed? Something that affects one of the Engineer's buildings?

For Medic..

Can the Practitioner's Pride's bleed effect last for a second longer? It being a projectile weapon that GREATLY slows you down is already gimping enough along with the slower health regen (fun fact, if you use it with the Healer's Shield, your health doesn't even regenerate at all while you have the Practitioner's out).

Can the Self-Preservation restore health on hit *instead* of gaining Uber? It'd make the name make a LOT more sense and would also help it move out of the Medic Right Arm's shadow since
well
that thing is just far better for gaining uber thanks to its higher clip size.
Also, can the move speed penalty be removed? It already has a switch speed penalty AND a reload speed penalty, I think thats enough speed penalties for one weapon. Having a third is just. Why.

And in order to make the Self-Preservation *not* overshadow the Doctor's Self-Care, can that increase Medic's health regen by 2 or more? And can its projectiles move a bit faster at the cost of a somewhat harsher damage penalty?

Can the Double-Shot have increased damage at the cost of having less reserve ammo? Right now it's.. just plain bad, honestly.

Can the G.U.P. Gun *also* have increased damage (not counting the crits)? Right now it feels marginally useful, especially when a Pyro can probably do a better job of applying Afterburn/Bleed.

Can the Cut Above's marked for death effect apply only when you miss? I don't really see the point in using it to kill someone when you'll get mowed down in a matter of seconds for most of the time with it out.

For Sniper..

Can the Sniper Right Arm have a MUCH faster firerate when unscoped? Right now it's somehow *worse* than before. Really.

Can the Alternate Big Game Hunter's damage bonus be nerfed to +20% instead of +30%? It's REALLY not very fun to fight against right now since the sniper doesn't even NEED to land a headshot to instantly kill a light class with it (125 or 150, doesn't matter).

Can the Deep Dive have a *slightly* faster firerate, or have a slightly increased clip size? Theres something about it that just makes it a little bit.. underwhelming. To me, it's making it into purely a Spy Counter Tool instead of making it generally good.

Can the Automatic Rifle deal a *bit* more damage? I have recently realized that it's meant to combo with most of Sniper's primaries, mainly the BMB and the Mann-Cannon, so having it deal a bit more damage per hit could make it an even better "combo" weapon.

Can the Karate! deal 40 damage per hit instead of 50? Right now it seems to be a fucking CRIT spawner with that faster firerate, causing it to kill people a LOT faster with 150 damage crits more often than not.

Can the Hack N' Slasher have an increased range? It LOOKS like a weapon that should have that stat, but. It doesn't, for some weird reason.

For Spy..

Can the Deagle Brand Deagle's move speed penalty be increased from -5% to -10%? Or even -17%? -5% move speed on a Spy of all things doesn't really impact a whole lot other than the Rapier weapon when the spy whips out the long sword.

Can the Unusual Unholy Reckoning be COMPLETELY reworked? Right now it's.. well it's kinda just a worse stock Tranquilizer.

Can the Spy Crowbar have a slightly extended range at the cost of having a slower swing speed? I think it'd only make a bit of sense for a weapon like it.

Can the Scarlet Rose's health drain penalty be removed, and can the move speed penalty be reduced to -20% at the cost of the bleed effect it applies lasting for only 4 seconds? Right now it's.. really not used seriously at all thanks to the HUGE speed penalty it applies when its active in combination to the fact that it DRAINS health.

Can the Contract Killer lower the Spy's max health by 25? Right now it is INCREDIBLY strong since it doesn't remove your disguise when you miss or land a hit with it.

Can the Whine Opener be changed into a pseudo Kunai by reducing the Spy's max health by 45, and also make the marked for death attribute only apply when you miss with it? I really don't see it used seriously considering how.. not that great it is.

For Civilian..

Can the Armstrongs give Health regen? Y'know. 'Cuz    N A N O M A C H I N E S ,    S O N    .

Can the Lord Of The House be either reverted or just completely REMOVED? As it is right now, it is WAY too strong of a support tool and is, as many have said, a better version of the Medic's Kritzkrieg.

Can the Backhand give the Civilian an increased movespeed, or can the swing speed penalty be slightly reduced? Right now it feels.. very eh. The fact that you have to risk your own life to knock ONE enemy away is.. way too damaging for a melee weapon on a class with only ONE loadout slot.

Lastly.. The Glory Kill.. Honestly, can the crits on kill be turned into Mini-Crits instead? With the marked for death penalty and damage bonus both being removed? Either that, or.. just remove it.

Alright, that is all I have to say for now! Again, sorry for posting a goddamn   T O W E R   of text.

**Comment by nosoytunose** [comment]
Ok ,i been noticing something with,what may be both of the worst pyro flames.afterburner and chemical ,what they have in common,they are both flames that focus in a seconary feature rather than direct damage....and thats why nobody uses them outside of memeing...so,why not merge both,a single flame that can deal 99% less damage,but has much stronger afterburn and the improved airblast and chemical,would do a great pybro flame,also a great tradeoff, knowing how strong is stock damage,because right now,i think both of these need a rework

**Comment by TheHopeBunny** [comment]
> Can the Prosecutor deal a LOT more damage?? Right now it.. barely does ANYTHING to enemies. Like, it literally deals around 5-8 damage per hit. This thing is a LOT worse than the Executor lol.

helo
uh
can the prosecutor actually do more than just tickle enemies when it actually hits them? right now it
well
it's literally just objectively worse than every single other pyro secondary in the mod
and pyro already has a problem with several of his primaries being not very good (COUGH molotov launcher COUGH)

**Comment by RurikArvallen** [comment]
Please remove the “add construction on hit” passive from the Storage Backpack and add it back to the Texas Strongmann. The Backpack doesn’t not need it nor does it benefit at all from it. The current stats are fine as it helps a turtling Engie be able to keep his buildings alive for longer but the passive is useless on it. It runs counter to the play style the Storage Backpack is meant to support. An Engie isn’t going to pull out his secondary to try and keep his buildings alive when he has access to wrenches that’ll do the job better. 

Another thing is please stop trying to take the passive away from the Texas Strongmann. You end up making it into an absolutely shit wrench for no reason. If you really want to balance it out, do something like give the Texas Strongmann a very high upgrade cost to the buildings like some of the other wrenches. It’ll help balance out the fact that an Engie with it equipped would need to deal more damage to get his buildings leveled rather than needing to just get around 3-5 shots with one of his shotguns to get to lv3.

**Comment by TheRealAtomicDemoman** [comment]
vogeljager needs a reload speed buff or increased mark for death time because you need to reload each shot it takes a long time and in that time you dont heal your teammates (what medic sould do) and they die faster which brings your team to defeat
the mark for death of vogeljager is really good for support but it makes you more defenseless when you got attacked and because of the low damage you need to use your melee (if you dont use medkit or baton)
so make it more useable for support and not in that weird state so you need to leave the beam to just mark for death and reload leaving teammates without healing.

**Comment by TheHopeBunny** [comment]
Can the Nail Storm have a higher clip size compared to the Rust Valley Relic? Right now it's just.. an objectively worse RVR. It's not quite *bad*, but it IS extremely outclassed by the RVR. I think it having a higher clip size could help differentiate it from the RVR instead of just having more reserve ammo.

**Comment by nosoytunose** [comment]
Speaking of remove...please remove the "minicrit boosted on hit of covert operator", because no shit, making your disguise's weapon glow bright green blows the point of the weapon. Unless its intentional and thats the point, and that is actually a downside. In that case... Pain? Idk right now contract killer is way better at the "dont remove disguise Job" both have similar premises with the difference that... One kills.

**Comment by Theoneofwonders** [comment]
> Speaking of remove...please remove the "minicrit boosted on hit of covert operator", because no shit, making your disguise's weapon glow bright green blows the point of the weapon. Unless its intentional and thats the point, and that is actually a downside. In that case... Pain? Idk right now contract killer is way better at the "dont remove disguise Job" both have similar premises with the difference that... One kills.

Not removing it, it helps people spot spies using the Covert Operator.

For the Contract Killer we're going to make it so if you take damage while disguised, you lose your disguise.

Honestly though I'm more rooting to remove the Contract Killer because I really don't like it's concept at all.

**Comment by TheHopeBunny** [comment]
can you remove the tale of tragedy's "turn invisible on kill" stat entirely? like, sure, it may fit thematically into the design of the weapon, but being unable to ATTACK while invisible really isn't that great. if it also increased SPEED on kill, then that may make it into the "kill and run" demoknight sword that it is VERY CLEARLY designed to be but almost fails to be good at.

**Comment by Theoneofwonders** [comment]
> can you remove the tale of tragedy's "turn invisible on kill" stat entirely? like, sure, it may fit thematically into the design of the weapon, but being unable to ATTACK while invisible really isn't that great. if it also increased SPEED on kill, then that may make it into the "kill and run" demoknight sword that it is VERY CLEARLY designed to be but almost fails to be good at.

I mean right now it doesn't even work lmao

I'll have a mess about with the invis and attack while invis thing though, I wonder if I can get it to work without having a repeat of the SCYTHE INCIDENT

**Comment by nosoytunose** [comment]
But... Yeah...magnet is a bit map dependant, like, rn is basically a straight upgrade to stock... But if you wanna use stock... Why not use the festive stick and get heal on kill and random crits.
The ability of the Magnet wrench to pick up buildings is good, but situational, specially with some wrenches were sometimes its better to self destroy than move the thing.
I think it would work better if you guys managed to remove the "on active", so damage actually affects buildings, but leaving it on only heal, not upgrade... We dont want the old fist 2.

(yes, kill no clue)

Btw, although i like the idea of adding dispenser range to it... Please dont do that... It doesnt add anything to the design of the weapon.

**Comment by TheHopeBunny** [comment]
so can you either revert or just remove the lord of the house? it's blatantly civilian's BEST choice right now due to the fact that right-clicking on someone to give them FULL crits for five whole seconds is uh
yeah it's kinda BUSTED
plus its damage downside doesn't really matter since
well
if a civilian wanted to use melee as an actual attacking option, they'd just switch to either armstrongs or glory kill (which is also still busted right now), hell maybe even just the stock umbrella
so yeah I suggest either reverting it to how it was before or just removing it entirely

**Comment by TheHopeBunny** [comment]
I think the Prosecutor as an *idea* is neat, but.. it really isn't very good in its execution as all its good for is lighting people on fire.

..something that Pyro is already supposed to be doing.

It also doesn't help that the Prosecutor barely tickles enemies on a direct hit with it, and if you wanted to reliably light an enemy on fire from a distance you could just swap to either the Flare Launcher or literally any of the Flare Guns in order to do that job.

The way I see it, the Prosecutor fails at being a *weapon* due to dealing barely any good damage and also fails at being a *tool* to apply afterburn simply due to how Pyro already has a LOT of weapons that set enemies on fire. It IS part of his job, after all.

So.. I suggest that it should either get buffed, receive some sort of rework, or just get removed from KOCW entirely.

**Comment by TheHopeBunny** [comment]
The Spitfire feels somewhat *underwhelming* given a combination of several downsides it has.

The weapon itself feels fun to use, but I'm not sure the upsides outweigh the downsides very much if at all
The -35% damage penalty is already a bit harsh for 2 extra rockets, then theres the +2 rocket deviation which.. I suppose I can live with if the damage penalty was a bit less, but then theres the -40% explosion radius penalty which seems WAY too harsh in combination with the other two real downsides the weapon has causing it to feel more of a downgrade from the stock Rocket Launcher. If the damage penalty was decreased to -25% and/or the explosion radius penalty was reduced to like -25% or something like that then the weapon would be a lot better at being a primary weapon.

**Comment by pro-medic-main** [comment]
The Bio-waste isn't really good for medic, considering he only has 150 health and weak damage, yet is supposed to go in FRONT of his patients. Maybe giving him +20/25 health would help? Feels like you NEED to use the Healer's Shield to not die instantly.

**Comment by TheHopeBunny** [comment]
Can the Combat Control receive a firerate buff? Right now, it generally feels pretty weak in comparison to the stock Stickybomb Launcher and the slow firerate is NOT helping. I understand that it's meant to deal damage *during* combat in comparison to stock which is meant to place traps, but like.. the Quickiebomb Launcher exists which completely invalidates that point seeing as how its a much more offensive version of stock. Even then, stock can be offensive too, especially the Minelayer.
Lower the damage of each hit to 50 instead of 54 (don't know why it's 54 specifically anyway) and increase the firerate a little bit.

**Comment by DJBiggieChegg** [comment]
With the addition of the Brick in 2.1, it'd be nice if Scout's Sandmate Secondary could be switched to use it as a base. I feel it gets held back currently by the charge mechanic that's inherent of it being a MIRV or Huntsman, whatever one it was.
Also if the effect is available, it should probably be changed to only slow opponents rather than tranqulise them. With you now getting crits from every melee, I could see it being too strong in combo with one of Scout's higher-damage melees.

The other thing of note is that both of Scout's primary pistols have a delay between the reload animation ending and the weapon being properly loaded. It's especially egregious on the revolver since its delay is over a second.

**Comment by nosoytunose** [comment]
Aight, here a little suggestion for the pilot light because... Stuff. _.
Pilot light is the only flaregun sidegrade that isnt "oh, now you can light up enemies easier"... But it suffers... A lot, yeah, at max ramp up is like 110 damage, and you also get the 'advantage' of rocket jumping, but in exchange, your  range is reduced by a lot, you get a shorter afterburn duration, what i feel, a slower proyectile, and worst of all, falloff, am sure it feels good landing a flare combo only to see 60 damage, and the upside of dealing more damage upclose and rocket jumping, gets deleted due to the fact that you delete half your hp bar in your own explotion... So... Yeah.
Reduce a bit of the self damage, increase proyectile speed the and remove the falloff

**Comment by TheHopeBunny** [comment]
Give Heavy cat claws as a melee weapon. For Le Funni.

**Comment by TheRealAtomicDemoman** [comment]
the scout's deagle and six shooter got the issues with reload animations not matching the actual reload speed, the six shooter suffers from this issue a lot because the reload speed is long and the reload animation of it is nowhere near the reload speed. is this intentional or not?

**Comment by superRadHazard** [comment]
The Artisans Artillery needs a buff or something to make it not a downgrade from stock. Sure the 67% increase in projectile speed is nice but the 67% slower firing speed makes in very hard to use… maybe give it the direct hits unique upside of mini criting airborne players? Or come up with something to make it’s faster pills useful, maybe give it a 25% increase in damage or explosion size? But at current moment it’s just not good

**Comment by superRadHazard** [comment]
The Mann Canon is really damn unfun to play against. It needs a nerf to make it not a straight upgrade to stock or any other weapon in general.

**Comment by RhynxSyn** [comment]
Is something gonna be done about explosive hitscan weapons? (Mann-cannon, Chain of Command and Anti Aircraft Cannon)

**Comment by Theoneofwonders** [comment]
2.1.1 will be releasing over the weekend to nerf the AA gun

As for Chain of Command and Mann-Cannon you're just gonna have to huff copium until v6.

**Comment by RhynxSyn** [comment]
im getting racist

**Comment by Animelored** [comment]
Please remove the mann-cannon from sniper, that weapon is so disgustingly overpowered that it genuinely ruins the game if there is even one person using it.

**Comment by Theoneofwonders** [comment]
> Please remove the mann-cannon from sniper, that weapon is so disgustingly overpowered that it genuinely ruins the game if there is even one person using it.

It's not being removed, but it will be adjusted when V6 launches this weekend.

**Comment by Animelored** [comment]
> 

Alright cool, just figured I'd echo the sentiment above since I did go onto a couple servers running the custom weapons and ask people, and it was almost universally agreed that it was somehow even worse than dealing with regular snipers, which is really saying something considering it's tf2.

**Comment by TheHopeBunny** [comment]
I personally have a question: Why remove the annoying hitscan explosive yet simply nerf the bullshit hitscan explosive? Wouldn't it make more sense to remove the Mann-cannon and nerf the Chain of Command's damage (and also stripping the mini-crits on hit attribute from it) while also giving it limited range?

**Comment by Theoneofwonders** [comment]
> I personally have a question: Why remove the annoying hitscan explosive yet simply nerf the bullshit hitscan explosive? Wouldn't it make more sense to remove the Mann-cannon and nerf the Chain of Command's damage (and also stripping the mini-crits on hit attribute from it) while also giving it limited range?

Soldier doesn't need the Chain of Command at all.

Mann-Cannon is getting a functionality rework to be more focused on taking down Tank subclasses (Tank Duty, Frag Master and W.A.L.L) while also removing what made it bullshit in the first place (one shotting anyone with 200 or less hp)

**Comment by RhynxSyn** [comment]
(it'll still one shot people with 200 or less hp)

**Comment by TheRealAtomicDemoman** [comment]
the weapon: brain hack is a bit too unfair to fight against since its a hitscan explosive with large damage
and stacking brain hack is absolute pain to deal with because they just 2 tap medics and soldiers

**Comment by Animelored** [comment]
> > I personally have a question: Why remove the annoying hitscan explosive yet simply nerf the bullshit hitscan explosive? Wouldn't it make more sense to remove the Mann-cannon and nerf the Chain of Command's damage (and also stripping the mini-crits on hit attribute from it) while also giving it limited range?
> 
> Soldier doesn't need the Chain of Command at all.
> 
> Mann-Cannon is getting a functionality rework to be more focused on taking down Tank subclasses (Tank Duty, Frag Master and W.A.L.L) while also removing what made it bullshit in the first place (one shotting anyone with 200 or less hp)

Sniper doesn't need the Mann Cannon either, I feel like the only people who actually like any of these instant death body shot sniper weapons are sniper players... and they don't count as people anyway.

**Comment by Mirrorman95** [comment]
My team and I spent the last match terrorized and constantly killed by a Scout who was utilizing a combination of the Rifleman's Runt and the Last Laugh. Why remove Heavy's laser guns and the Doom Civilian but add a rifle that makes Scouts into nigh-unstoppable Snipers? The point is, the Last Laugh and especially Rifleman's Runt should either be nerfed or removed.

**Comment by TheRealAtomicDemoman** [comment]
> My team and I spent the last match terrorized and constantly killed by a Scout who was utilizing a combination of the Rifleman's Runt and the Last Laugh. Why remove Heavy's laser guns and the Doom Civilian but add a rifle that makes Scouts into nigh-unstoppable Snipers? The point is, the Last Laugh and especially Rifleman's Runt should either be nerfed or removed.

rifleman's runt is kinda bad unless you can noscope headshot. the last laugh is straight up a rocket jumper secondary but for scout, though the knockback vs enemies is really funny

**Comment by TheHopeBunny** [comment]
So is there any plans to nerf the Gauss Gun?

**Comment by Reagy** [comment]
> So is there any plans to nerf the Gauss Gun?

Yes, I'm redoing its model to work off the rifle version, it'll also have a fixed ammo pool and a mild damage penalty to bring its overall damage down.

**Comment by TheHopeBunny** [comment]
So, um. Problem with the Second Ammendment to make Wonders aware of it:

It's upside of refilling your magazine on kill?

Yeah that part's *passive*. And it can allow a Soldier to *not* use the SA since this passive upside can now encourage them to spam the RPG literally everywhere without a single care in the world.

Pls change it to while the SA is active.
