### ISSUE TITLE
Sugg: Civ Adjustments

### ISSUE THREAD

**Issue by Plaguewalker** [Reagy/TF2Classic-KO-Custom-Weapons#128]
Hello,

As, I'll get straight to the point there is quite vocal minority that find civs capture rate abhorrently busted on say Attack Defend, Control points and payload. While yes the last one only counts 3 out of 5 in his capture rate pool. The rest do not, as I am acutely aware his rate is tied and hardcoded preventing any actual adjustment so I'm suggesting a work around across the board on **_ALL_** of his weapons barring the umbrella. As it is possible to lower the capture rate on a class the fox item being an example. My suggestion is lower his rate to that of the base scouts x2. The umbrella itself acts as stock allowing its x5 to be left alone. With a x2 on all his weapons it still allows him to be useful without being dead weight/a wasted slot for the meme class.

**Comment by RhynxSyn** [comment]
having x2 on other weapons wouldnt make them viable for playing the objective, which is one of the civ's main jobs. having him be as fast as the scout would make him even worse. it wouldnt be fair for people that want to play civ to have their main class skill to be changed because they want a revolver for self defence or want to slap people away or slow them instead of having stock

**Comment by Plaguewalker** [comment]
> having x2 on other weapons wouldnt make them viable for playing the objective, which is one of the civ's main jobs. having him be as fast as the scout would make him even worse. it wouldnt be fair for people that want to play civ to have their main class skill to be changed because they want a revolver for self defence or want to slap people away or slow them instead of having stock

Yes, but this is a much reasonable option than the full nuclear of wiping his rate to x1 for all his weapons barring the umbrella. Personally, coming back to this maybe x2 or x3 is the best we can get. While yes, Civ's main focus on here is a sort of crappy jack of all trades on here as well as capturing points. The bottom line is he shouldn't be capturing points alone in a matter of seconds without having a team. He's pretty much a high pick target akin to say the medic. Because, with how he already passively buffs the team with a defense buff in a small AoE near him while also able to dispense mini-crits/crits/Marked for Death/Repair/Heal depending on his kit chosen.

**Comment by RhynxSyn** [comment]
Civ's removal of minicrits is the "downside" to having the other weapons. Giving Civ no minicrits AND less capture rate makes him useless to the team. The reason he captures fast is because he can't fight for himself, along with needing his team to protect him. If the team has their point capped by a single Civilian without protection that isn't a balance issue, that's a skill issue of how the team can't protect the point to notice the little British man that can't do anything coming along.
