### ISSUE TITLE
Soft fix to recosntrunction syrup (melee)

### ISSUE THREAD

**Issue by nosoytunose** [Reagy/TF2Classic-KO-Custom-Weapons#194]
![image](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/103970720/b9aee260-331e-4d87-8149-39840d122b10)
Sometimes ,while using the right click,it just doesnt work,you save the syrup to the last moment to save your patient,and it doesnt work,and your patient dies,while you get marked for eath for no reason,i would suggest changing it to give a civ aura,since at l east if it doesnt worjk,there isnt hat much punishment

**Comment by RhynxSyn** [comment]
Personally I believe that the Reconstruction Syrup should be completely reworked on it's alt fire.

Ubercharging someone doesn't help them, it makes them think they got fully ubered and will run into the enemies on super low health.

Instead why not change this into an escape weapon, giving the medic a short leap on a melee hit. Because let's be honest, people use this to escape and heal, not to save people with the ubercharge.
