### ISSUE TITLE
The Problem With Medic (Heal rates, items and combat)

### ISSUE THREAD

**Issue by pro-medic-main** [Reagy/TF2Classic-KO-Custom-Weapons#212]
Currently, Medic is one of the most overpowered classes right now (as he should be), but when it comes to Medic as a whole, he is too powerful and does not work right in TF2.

Let's talk about the primaries first.

To me, medic's primaries (and also weapons) come into three types:

Defence (Mostly syringe guns)
Offence (Mostly hitscan/fast projectile guns, the main problem)
Support (Misc. items)

_**Primary Defence**_

Primary defence is one of the most optimal uses for an actual Medic primary weapon. These weapons are basic syringe guns like stock, rewarding the Medic for hitting shots with exceptional damage to fend off enemies.

The syringe gun's slow and clunky projectiles makes it so that pushing in will probably make you land less shots, this is why it is easier to hit syringes while moving backwards, away from enemies.

Defence primaries are used so that the Medic can be able to survive encounters with enemies when by himself, while also dealing damage to enemies and retreating to teammates for assistance.

Defence primaries should be one out of the two types that should be a main part of medic's primaries.

_**Primary Support**_

These are really good for Medic, making you rely on your team more due to the lack of a damage dealing primary in return for you outputting more heals.

These kinds of primaries are to show that you are willing to trust your team and keep them alive longer than possible so you are able to stay in the safety of your team. High risk (risk being no defence by yourself) in return for high reward (high heals).

_**Primary Offence**_

This is the worst kind of Medic primaries overall.

This is assuming you would want to revolve Medic around healing, which is what I ASSUME that the developers want due to their removal of the Oathbreaker, therefore removing combat Medic.

Most of these weapons are a huge problem, as weapons like the Super Nail Gun, Medical Administration and Spas-12 encourage the Medic to STOP HEALING (Medic's main job) which would decrease the survival of the team overall.

The one rule that should be made when giving Medic weapons is that HE SHOULD NOT HAVE A SHOTGUN. Giving Medic a shotgun makes him have no downsides at all, making him the most overpowered character.

Speaking of primary offence, there are weapons that slow the Medic down. This is a HORRIBLE idea, as you make it so the class whose main ability is to run away worse in return for a syringe gun that shoots slow and has around the same/less damage output than stock.

_**Fixing Primaries**_

Fixing Medic's primary weapons are very simple, revolve them around defence syringe guns and Misc. items.

Instead of being Defence, Offence and Support, why not make the three types of weapons Defence, Support and Survivability?

Survivability weapons would be Misc. items that would help you survive and escape encounters.
The speedy recovery was a perfect example of this, as it put you in high risk when escaping in return for high mobility so you can easily run away.

Some other examples of "Survivability weapons" would be:

- More health or more effective health (A helmet that would lower headshot damage? Body armour? Bonus health regen?)
- Applying effects within Medic's range (Slow/Stunned effect or a screen shake to enemies?)
(Screen shake worked REALLY well with Medic before, it made it easy for people to lose where you went)

_**Melee Weapons**_

Unlike the Primary weapons, there isn't really that much of an option. It's either the Medkit, Cut Above or Uberspritze.

- Stock used to be good but the Cut Above exists, along with the Uberspritze dealing random crits too.

- Blood Donor slows (Slow for Medic is bad)

- Healer's Shield slows (Slow for Medic is bad)

- Medkit does what Shock Therapy does but better

- Defibrillator is useless. If you need a pocket one shot you or your team isn't doing something right. And nobody uses it for the insta-heal. (Not to mention it removes Uber)

- Festive Twig seems good until someone decides to go a high mobility class with the Twig to one shot you

The two new Medic melee weapons are really good, and are taking the step of helping yourself survive and escape more.

The best way to improve Medic weapons are to just remove all of the bad ones, keep the good ones (Medkit, Cut Above, Syrup and Sensory Overload) and focus more on support and survivability

Some examples of this are:

- Applying friendly buffs (Minicrits, Defence boost, something like the Disciplinary Action)
- Getting survivability for defence (Blood Donor would be good without the speed debuff)
- Boosts for killing with melee? (25% healing rate with a melee kill for 5-10 seconds?)

_**Mediguns and Healing Rate**_

To be honest, the Mediguns are horrible. The main Mediguns that're the problem are the Booster Shot, Bio-Waste and Guardian Angel.

_**Booster Shot**_

This weapon is an abomination. While you can't compare apples to oranges, the Booster Shot is overpowered compared to the TotenWerfer and any other Medigun that isn't the GA or Stock.

Having 75% heal rate and a 10% speed boost for Medic is terrifying, but 100% with the Geared-up Ghost (a primary that Medics would use for optimal healing) is insane. I'm convinced the Geared-up Ghost got nerfed from 30% to 25% was because of this weapon and the Bio-Waste.

Why not instead of just being blatantly overpowered, just have some fun with this weapon?
You could do multiple stuff with the Medigun being called the "Booster Shot"

Why not make it stock with a 50-75% Ubercharge rate at the cost of a different Uber.

Some ideas I'd like would be:

- A health boost, restoring the targets health, but instantly using the Uber.
- Haste boost, maybe a radius or just between the Medic and Patient? Would be really fun and would cause chaos similar to the Kritzkrieg.

You could do so much with this weapon, yet it just turns generic and overpowered.

_**Guardian Angel**_

There's no saving this weapon, it doesn't matter if it's 80 damage or 2 Ubercharges, this weapon is still overpowered.

If you can block a backstab, fully charged sniper headshots and even a fully charged BFG then this weapon has something wrong with it.

The main problem is the Ubercharge, so why not change it?

Instead of making it a mini-Uber, let's make it a mini-totenwerfer.

Let's make it so that the Ubercharge give you a defence buff, but giving you critical heals for 3-5 seconds. I also feel like you should tone down the Ubercharge rate, making it 33% instead of 66% as Uber decay doesn't happen due to the -50% max overheal, resulting in a 110% Ubercharge rate.

_**Bio-Waste**_

Just throw this in the bin.

Nobody actually likes this Overwatch 2 Moira lookin ah musty crusty trash pipe lookin ah medigun.

Horrible healing rate, horrible damage at the cost of health steal, which you wouldn't need if you weren't using the Medigun offensively.

If you want to actually make this good, do something interesting.

Remove the healing rate, remove the Ubercharge rate and make it so you can gain Ubercharge off of enemies, dealing damage rewards an Ubercharge bonus instead of just healing, so you get more Uber dealing damage than healing teammates, making it (kind of) worth it.

Instead of making the Ubercharge generic healing aura, why not make it a mini-crit radius? Imagine leading a whole group of teammates to rush down the enemies as everyone is buffed up with mini-crits. Who wouldn't want that to happen? (Aside from the enemy team.)

Overall, while Medic is overpowered and leans on the offensive side, he should be toned down a bit and should focus on Defence, Support and Survivability.

Hope you read this and consider reworking Medic.

**Comment by Theoneofwonders** [comment]
I can't take any of this seriously, I'm sorry.

**Comment by pro-medic-main** [comment]
What?

**Comment by Theoneofwonders** [comment]
Alright, I'll humour you.

Let's go through this one by one, yes?

> Let's talk about the primaries first.

To me, medic's primaries (and also weapons) come into three types:

Defence (Mostly syringe guns)
Offence (Mostly hitscan/fast projectile guns, the main problem)
Support (Misc. items)

> Primary Defence

Primary defence is one of the most optimal uses for an actual Medic primary weapon. These weapons are basic syringe guns like stock, rewarding the Medic for hitting shots with exceptional damage to fend off enemies.

The syringe gun's slow and clunky projectiles makes it so that pushing in will probably make you land less shots, this is why it is easier to hit syringes while moving backwards, away from enemies.

Defence primaries are used so that the Medic can be able to survive encounters with enemies when by himself, while also dealing damage to enemies and retreating to teammates for assistance.

Defence primaries should be one out of the two types that should be a main part of medic's primaries.

Entirely moronic argument, what the fuck do you mean it's easier to hit syringes when moving backwards that's not how this works.

Also your wording of this implies that they're better off used offensively since they have high damage...

> Primary Offence

This is the worst kind of Medic primaries overall.

This is assuming you would want to revolve Medic around healing, which is what I ASSUME that the developers want due to their removal of the Oathbreaker, therefore removing combat Medic.

Most of these weapons are a huge problem, as weapons like the Super Nail Gun, Medical Administration and Spas-12 encourage the Medic to STOP HEALING (Medic's main job) which would decrease the survival of the team overall.

The one rule that should be made when giving Medic weapons is that HE SHOULD NOT HAVE A SHOTGUN. Giving Medic a shotgun makes him have no downsides at all, making him the most overpowered character.

Speaking of primary offence, there are weapons that slow the Medic down. This is a HORRIBLE idea, as you make it so the class whose main ability is to run away worse in return for a syringe gun that shoots slow and has around the same/less damage output than stock.

Blame NotClue for removing the Oathbreaker, he couldn't be bothered to fix it and neither of us were interested in re-instating combat medic.

Medical administration is a SUPPORT weapon as it gives you UBERCHARGE BONUS for shooting people with it, it doesn't matter if it's hitscan as it's primary benefit is buffing your uber rate...

Super Nail Gun is a DEFENSIVE weapon as you don't have enough ammo to engage enemies reliably with it, nevermind the slow nail speed and recoil making it hard to hit nails (oh and it barely does more DPS than stock, fyi).

We have the Doctor's Self-Care for survivability too as it heals you for shooting enemies while running away.

We removed the heart throwing weapon because screen shake is never a good idea, no matter what you do with it.

> Melee Weapons

Unlike the Primary weapons, there isn't really that much of an option. It's either the Medkit, Cut Above or Uberspritze.

Stock used to be good but the Cut Above exists, along with the Uberspritze dealing random crits too.

Blood Donor slows (Slow for Medic is bad)

Healer's Shield slows (Slow for Medic is bad)

Medkit does what Shock Therapy does but better

Defibrillator is useless. If you need a pocket one shot you or your team isn't doing something right. And nobody uses it for the insta-heal. (Not to mention it removes Uber)

Festive Twig seems good until someone decides to go a high mobility class with the Twig to one shot you

Blood Donor is one of medic's best melees because it life steals, meaning enemies marked for death or tranquilized give you MORE health if you hit them with this. 

Healer's Shield downsides are worth the extra health, the speed penalty is rather minor if you just.. keep in the backline?

Defib is better than you think it is, don't diss on the ability to delete a spy that you end up catching in the corner of your eye (or one-shotting a poorly-placed sentry gun or teleporter..)

Twig is a shitpost weapon, if you use it you better be ready to accept the consequences of being a clown.


I will also IMMEDIATELY dismiss most of your medi-gun feedback, holy fuck you really lost brain cells at this part.

First of all you have to understand how powerful the stock medi-gun is by default, being able to make someone INVINCIBLE FOR EIGHT SECONDS is not a joke at all.

The Booster Shot is powerful, but it's far from overpowered.

Medic's power is 90% on that Ubercharge, if you don't have a good Uber, you're practically dead weight in most circumstances.

Having the ability to provide burst healing is a strong thing to have, but your pocketing is heavily discouraged with the abysmal uber rate on overhealed patients.

The fact you called the Guardian Angel basically irredeemable is hilarious, you really are something.

This weapon used to be leaps and bounds more powerful that it is now, and I would call this a reasonable balanced item.

I don't get why you would drag this thing through the mud so much, a mini-totenwerfer style uber would kill this weapon completely.

The only thing you got right about the medi-gun analysis is the Bio-Pump, and that's all the credit I'll give you.

Medic is powerful, yes, but he is by all means not overpowered.

Team balance is a bigger factor in medic's viability than his arsenal, which is mostly full of mostly acceptable weapons in terms of both internal and external balance.

Medic will naturally receive balance changes heading into 6.1, so it's not an entirely lost cause.

However consider the fact that I just had Reagy tell me that you're an actual clown and the shit you have posted here in the past would make me believe that you might be fitting of such a title.

I can't believe I have wasted almost half an hour replying to this complete eyesore of a post.

And you call yourself a "pro medic main", geez.

**Comment by pro-medic-main** [comment]
1. It is easier to hit syringes when moving backwards? Have you never used a syringe gun before? You literally do hit more syringes when walking backwards if your enemy is chasing you due to the fact you aren't going towards THEM instead while the syringe projectile is still travelling.

No idea where you got the point where syringe guns should be an offensive weapon.


2. If you're going to remove the main battle medic medigun you should atleast try and do something as a replacement, you make it seem like Battle Medic is an invalid sub-class which it mostly is due to the Oathbreaker's removal.

While the Medical Administration is a """Support""" weapon and giving you an Ubercharge bonus, it stops you from healing your team in which you could be gaining Ubercharge while healing. Dealing damage for a slightly better Ubercharge rate at the cost of wasting potential Ubercharge and at the cost of teammaates literally dying is not that """supportive""" for you or your team.

Doctor's Self-Care leans towards defence and survivability, though while it gives health, it does not give any advantage to the Medic when escaping a situation. You aren't going to be able to outheal and outdamage a soldier, which is why instead of fighting back rocket/damage surface is a technique for Medic players. 

What's the point of the Super Nail Gun if all it does "barely more DPS than stock", why not remove it at that point? You basically just said that it's a weapon that doesn't need to exist, as the Syringe Gun and Doctor's Self-Care do the job of defence better.

Screen shake was just a suggestion, as I found myself to be able to escape multiple encounters with it, other examples could be used instead of screenshake like slowness.

3. Blood Donor is a bad weapon as you will rarely use it with your team and will be at a disadvantage when pulling it out as self-defence by yourself. The fact you needed to use examples like tranq and mark for death along with adding the invisible stat of critting overhealed players (didn't check if it was removed yet) shows how bad it is and needs a fix to it.

Healer's Shields downsides aren't worth the extra health as if you ARE in the backline the worst that can get you is a Sniper (who is completley butchered and rarely headshots Medic) a random Scout in which the shield MIGHT protect you from an extra shot or a Spy which doesn't deal much damage and could easily be taken care of with a viable melee. 

Defib is not better than I think it is. If there's a Spy you tell your team or use a weapon that doesn't hinder your Ubercharge (not that supportive). I'm going to completely ignore that last part as it's stupid to think that MEDIC should be the main person to take out sentries and dispensers compared to the other multiple classes that can do it. (Not to mention if you attack the Spy and he's disguise it fully heals him.)

Twig is fine as it is if you're considering it as a shitpost weapon.

4. Do not say that Medic's power is based on his Ubercharge when you gave Medic a POTENTIONALLY 100% HEALING RATE.

While stock uber is good for pushing, I have barely seen any pushes that really needed a stock ubercharge in this gamemode. Comparing that to the Booster Shot which can keep a shit ton of people alive extremely quickly. Also have to mention the multiple knockback items and slow items that stall stock and make it useless, compared to the 30 seconds booster shot uber.

Stock uber is GOOD, but it's not as good as the others compared to Medic's alternatives and other weapons that hinder stock uber. (Haven't seen a stock uber shutdown an engineer nest in ages.)

Pocketing isn't really that discouraged due to the """support""" weapon the Medical Administration along with the Uberspritze. If you're saying the Blood Donor and Defib is good then you probably think you can easily get a melee in as Medic, meaning that you'll easily get Booster Shot Uber pretty quickly, completely invalidating the whole "anti-pocket" downside.

The Guardian Angel is still irredeemable. It is not balanced and people are still complaining about it. I literally listed things you can survive that would usually put you in a grave and far below 6 feet, yet you claim it's balanced with its 110% ubercharge rate. What's more hilarious is that you think it's balanced.

Difference between my suggestion and your weapon, is that I'm actually realising the problem and trying to give suggestions to solve it, meanwhile you think "mmmm yes 110% ubercharge rate along with half uber required." Do you hear yourself? You basically gave one ubercharge the effective ubercharge rate of 210% because you have reduced the requirement for one charge by HALF. 

While my suggestion wasn't good, the current weapon isn't good either.

Team balance is infact a bigger factor into medic's viability, that's why I suggested that offensive weapons are a bad option. If your team is balanced and is doing GOOD then you should equip a support weapon to help with you healing and keeping your team alive. If your team is doing BAD you should equip a weapon that is based on defence/survivability.

The fact you believe Medic should have offensive weapons and a literal shotgun despite the fact that Medic is a class that's main weakness is being defenceless due to the power of his healing and Ubercharge confuses me.

I'd call you a bad developer, but you ain't developing that much aside from complete garbage weapons. Everyone talks shit about you but barely any other weapon creators, because most of the weapons you have made have caused problems to the balance. Play some live TF2 Medic and learn how Medic should be played properly, make sure to pull up to the TF2C discord when you're done... oh wait... you can't!!!

(Image was taken of you and Reagy's discussion)
![image_2023-07-15_030113390](https://github.com/Reagy/TF2Classic-KO-Custom-Weapons/assets/113937923/925b7871-07cc-4967-bc94-808d46e53db1)
